import { expect, test, type Route } from "@playwright/test";

test("animates only the active frame, advances through the queue and stops on cancellation", async ({ page }, testInfo) => {
  const pending: Route[] = [];
  await page.route("**/api/generate-panel-image", route => { pending.push(route); });
  await page.goto("/");
  await page.getByLabel("01 / Scene idea", { exact: true }).fill("Two explorers follow footprints across an empty moon.");
  await page.getByLabel("Panels", { exact: true }).selectOption("4");
  await page.getByTestId("generate-button").click();
  await page.getByTestId("generate-all-images").click();
  const first = page.getByTestId("panel-image-1");
  const second = page.getByTestId("panel-image-2");
  await expect(first.getByRole("status")).toHaveText("Generating image…");
  await expect(second).toContainText("Waiting to generate");
  await expect(second.getByTestId("image-generation-placeholder")).toHaveCount(0);
  expect(await first.locator(".image-generation-scan").evaluate(element => getComputedStyle(element).animationName)).toBe("image-frame-scan");
  await first.scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath("generating-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await first.scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath("generating-mobile.png") });
  await page.emulateMedia({ reducedMotion: "reduce" });
  expect(await first.locator(".image-generation-scan").evaluate(element => getComputedStyle(element).animationName)).toBe("none");
  await expect(first.getByRole("status")).toBeVisible();
  await expect.poll(() => pending.length).toBe(1);
  await pending[0].continue();
  await expect(first.getByRole("img")).toBeVisible();
  await expect(first.getByTestId("image-generation-placeholder")).toHaveCount(0);
  await expect(second.getByRole("status")).toHaveText("Generating image…");
  await expect(page.getByTestId("panel-image-3")).toContainText("Waiting to generate");
  await page.getByRole("button", { name: "Cancel image generation", exact: true }).click();
  await expect(page.getByTestId("image-generation-placeholder")).toHaveCount(0);
  await expect(page.getByTestId("panel-image-3")).toContainText("Image not generated");
  await expect(first.getByRole("img")).toBeVisible();
  expect(pending.length).toBe(2);
  await pending[1].abort().catch(() => {});
});

test("shows an animated alternative while keeping the current image visible", async ({ page }, testInfo) => {
  await page.goto("/");
  await page.getByLabel("01 / Scene idea", { exact: true }).fill("A robot tends a garden beneath an alien ocean.");
  await page.getByTestId("generate-button").click();
  await page.getByRole("button", { name: "Generate image for panel 1", exact: true }).click();
  const first = page.getByTestId("panel-image-1");
  await expect(first.getByRole("img")).toBeVisible();
  const original = await first.getByRole("img").getAttribute("src");
  let pending: Route | undefined;
  await page.route("**/api/generate-panel-image", route => { pending = route; });
  await page.getByRole("button", { name: "Regenerate image for panel 1", exact: true }).click();
  const dialog = page.getByRole("dialog", { name: "Regenerate image", exact: true });
  await expect(dialog.getByTestId("image-generation-placeholder")).toBeVisible();
  await expect(page.getByTestId("panel-image-2")).toContainText("Image not generated");
  await expect(dialog.getByRole("img", { name: "Current image for panel 1", exact: true })).toHaveAttribute("src", original!);
  await page.screenshot({ path: testInfo.outputPath("generating-alternative.png") });
  await expect.poll(() => Boolean(pending)).toBe(true);
  await pending!.continue();
  await expect(dialog.getByRole("button", { name: "Use this image", exact: true })).toBeEnabled();
  await expect(dialog.getByTestId("image-generation-placeholder")).toHaveCount(0);
  await dialog.getByRole("button", { name: "Keep current", exact: true }).click();
  await expect(first.getByRole("img")).toHaveAttribute("src", original!);
});
