import type {
  StoryboardInput,
  StoryboardPackage,
  StoryboardPanel,
} from "@/types/storyboard";

const basePanels: StoryboardPanel[] = [
  {
    panelNumber: 1,
    storyBeat: "A lone figure moves through an apparently lifeless station.",
    shotType: "establishing shot",
    cameraDirection: "Wide, locked-off frame down the corridor; the astronaut enters from deep background.",
    action: "The astronaut advances through floating dust and loose cables, helmet light scanning the dark.",
    setting: "Abandoned space station corridor",
    imagePrompt: "Cinematic live-action sci-fi frame, wide view of a tired astronaut in a worn white suit crossing a dark abandoned station corridor, flickering red emergency lights, floating dust, loose cables, cold metal walls, deep shadows, realistic film lighting, precise symmetrical composition",
    negativePrompt: "No aliens, explosions, crowds, glossy clean surfaces, cartoon rendering, or cheerful lighting",
    dialogueOrNarration: "No dialogue. Breathing and distant metal strain.",
    productionNote: "Establish isolation and the protagonist's physical exhaustion in one economical image.",
  },
  {
    panelNumber: 2,
    storyBeat: "A faint green reflection interrupts the monochrome corridor.",
    shotType: "medium shot",
    cameraDirection: "Frame from behind the astronaut, holding the green glint just beyond their shoulder.",
    action: "The astronaut stops and angles their helmet light toward a cracked wall panel.",
    setting: "Corridor threshold",
    imagePrompt: "Medium rear view of a worn astronaut noticing a faint green glow inside a cracked station panel, subtle green reflection across scratched visor, dark industrial interior, restrained suspense, realistic cinematic lighting, shallow atmospheric haze",
    negativePrompt: "No monster, weapon, neon cyberpunk overload, action pose, or excessive lens flare",
    dialogueOrNarration: "The astronaut's breathing pauses.",
    productionNote: "Introduce the visual mystery and pivot the scene from resignation to curiosity.",
  },
  {
    panelNumber: 3,
    storyBeat: "The source of the glow is revealed as a tiny living plant.",
    shotType: "close-up",
    cameraDirection: "Floor-level close-up; focus stays on the plant as a gloved hand enters frame.",
    action: "A gloved hand brushes dust from a tiny shoot growing through a seam in the floor.",
    setting: "Observation bay floor panel",
    imagePrompt: "Intimate cinematic close-up of a tiny green plant emerging through cracked cold metal inside an abandoned space station, large astronaut glove brushing away dust, soft green against grey steel, shallow depth of field, fragile hopeful mood, realistic live-action sci-fi",
    negativePrompt: "No oversized plant, magical particles, cartoon flower, garden soil, or outdoor sunlight",
    dialogueOrNarration: "Astronaut, barely audible: “How are you still alive?”",
    productionNote: "Reveal the central motif clearly and let scale create emotional weight.",
  },
  {
    panelNumber: 4,
    storyBeat: "The astronaut chooses to protect the fragile discovery.",
    shotType: "medium shot",
    cameraDirection: "Slight handheld tilt as the room shudders, then settle on the astronaut shielding the plant.",
    action: "A ceiling fragment falls; the astronaut quickly covers the plant with both hands.",
    setting: "Observation bay",
    imagePrompt: "Cinematic medium shot of a tired astronaut kneeling and shielding a tiny plant from falling debris, flickering emergency light, Earth dimly visible through curved glass, controlled urgency, realistic film composition, hopeful sci-fi drama",
    negativePrompt: "No large explosion, battle, monster, death, or catastrophic destruction",
    dialogueOrNarration: "No dialogue. A sharp exhale as the debris settles.",
    productionNote: "Turn observation into action, showing the protagonist's emotional commitment.",
  },
  {
    panelNumber: 5,
    storyBeat: "The astronaut works out how to move the plant safely.",
    shotType: "over-the-shoulder",
    cameraDirection: "Over the astronaut's shoulder toward the cracked panel and a makeshift tool laid beside it.",
    action: "They loosen the panel carefully without disturbing the plant's roots.",
    setting: "Observation bay floor",
    imagePrompt: "Over-the-shoulder cinematic frame of an astronaut delicately loosening a cracked metal panel around a tiny plant, improvised hand tool, focused helmet light, tactile worn materials, restrained green accent, realistic live-action production design",
    negativePrompt: "No advanced laboratory, extra crew, fantasy tool, clean surfaces, or rapid action",
    dialogueOrNarration: "Only careful tool clicks and breathing.",
    productionNote: "Make the rescue mechanically credible and give the action a readable intermediate beat.",
  },
  {
    panelNumber: 6,
    storyBeat: "The plant is carried toward the observation window.",
    shotType: "tracking shot",
    cameraDirection: "Slow lateral track with the astronaut's hands; reveal Earth as they cross frame.",
    action: "The astronaut carries the loosened panel toward the cool light at the window.",
    setting: "Observation bay",
    imagePrompt: "Slow tracking composition of astronaut hands carrying a cracked metal panel with a tiny green plant toward a vast observation window, blue Earth emerging outside, soft reflected light, abandoned equipment in shadow, emotional realistic sci-fi cinema",
    negativePrompt: "No magic, crowded crew, pristine laboratory, exaggerated plant growth, or cartoon style",
    dialogueOrNarration: "Astronaut: “Easy.”",
    productionNote: "Connect the plant visually to Earth and carry momentum into the resolution.",
  },
  {
    panelNumber: 7,
    storyBeat: "Earthlight reaches the leaves for the first time.",
    shotType: "extreme close-up",
    cameraDirection: "Macro push-in on one leaf as blue-white light travels across its surface.",
    action: "The plant trembles, then opens slightly in the window light.",
    setting: "Observation window ledge",
    imagePrompt: "Extreme close-up macro film frame of a tiny green leaf opening in soft blue Earthlight, droplets of condensation, brushed metal beneath, astronaut reflected faintly in glass, subtle hopeful transformation, photoreal cinematic detail",
    negativePrompt: "No instant giant growth, sparkles, fantasy aura, saturated neon, or text",
    dialogueOrNarration: "The station ambience falls almost silent.",
    productionNote: "Use a small physical change as the emotional climax rather than spectacle.",
  },
  {
    panelNumber: 8,
    storyBeat: "The astronaut's expression softens behind the damaged visor.",
    shotType: "close-up",
    cameraDirection: "Tight frontal portrait with the plant and Earth reflected across the visor.",
    action: "The astronaut watches the leaf and allows a small, exhausted smile.",
    setting: "Observation window",
    imagePrompt: "Tight cinematic portrait of an exhausted astronaut behind scratched helmet glass, tiny plant and blue Earth reflected in visor, eyes softening into a restrained smile, low-key realistic lighting, melancholic hopeful sci-fi drama",
    negativePrompt: "No broad grin, glamour portrait, clean helmet, tears floating theatrically, or bright studio light",
    dialogueOrNarration: "No dialogue.",
    productionNote: "Pay off the internal arc through performance and reflection, without exposition.",
  },
  {
    panelNumber: 9,
    storyBeat: "The astronaut settles beside the plant instead of moving on.",
    shotType: "wide shot",
    cameraDirection: "Wide profile composition, astronaut and plant small against the window and Earth.",
    action: "The astronaut sits on the floor, checking the plant's position as the station steadies.",
    setting: "Observation bay window",
    imagePrompt: "Wide profile film frame of a lone astronaut seated beside a tiny plant at an abandoned station window, immense blue Earth beyond, cool ambient light, decayed machinery in silhouette, quiet balanced composition, realistic contemplative sci-fi",
    negativePrompt: "No spacecraft battle, additional characters, dramatic pose, fantasy landscape, or title text",
    dialogueOrNarration: "Breathing slows into the room tone.",
    productionNote: "Let the scale of the frame contrast cosmic distance with intimate care.",
  },
  {
    panelNumber: 10,
    storyBeat: "The station remains broken, but no longer feels empty.",
    shotType: "establishing shot",
    cameraDirection: "Slow pull back through the bay doorway, leaving astronaut and plant framed together.",
    action: "The astronaut and plant remain in Earthlight as the corridor foreground returns to shadow.",
    setting: "Observation bay and corridor",
    imagePrompt: "Final cinematic establishing frame pulling back from an abandoned station observation bay, astronaut and tiny green plant together in a pool of blue Earthlight, dark corridor framing the image, minimal composition, melancholic hopeful ending, realistic live-action film still",
    negativePrompt: "No explosion, rescue ship, fantasy creature, triumphant pose, bright happy ending, or text",
    dialogueOrNarration: "No dialogue. Quiet breathing fades into ambient silence.",
    productionNote: "Close on a resolved visual relationship while preserving the world's loneliness.",
  },
];

export function createMockStoryboard(input: StoryboardInput): StoryboardPackage {
  return {
    title: "The Last Green Thing",
    logline: `${input.sceneIdea.replace(/[.!?]+$/, "")}, creating a ${input.tone.toLowerCase()} turning point in an otherwise silent world.`,
    genre: input.genre,
    tone: input.tone,
    visualStyle: input.visualStyle,
    estimatedDuration: input.duration,
    characters: [
      {
        name: "Astronaut",
        role: "protagonist",
        visualDescription: "A tired astronaut in a worn white suit with scratched helmet glass, dim suit lights, and slow, heavy movements.",
        personality: "Lonely, exhausted, careful, and quietly hopeful.",
      },
    ],
    locations: [
      {
        name: "Abandoned Space Station",
        description: "Cold metallic corridors lead to a curved observation bay filled with dust, loose cables, and dormant equipment.",
        mood: "Silent, isolated, and gradually tender.",
      },
    ],
    storyboard: basePanels.slice(0, input.panelCount).map((panel, index) => ({
      ...panel,
      panelNumber: index + 1,
    })),
    continuityNotes: [
      "Keep the astronaut's suit worn, scratched, and slightly dirty in every panel.",
      "The plant remains tiny and fragile throughout the sequence.",
      "Use green as the only organic accent against the station's cold neutral palette.",
      `Maintain a measured visual rhythm appropriate for ${input.duration}.`,
    ],
    productionNotes: [
      "Build the scene around the contrast between mechanical decay and organic life.",
      "Keep dialogue minimal so framing, action, and sound carry the emotional meaning.",
      "The sequence is achievable with one performer, one principal set, and one practical plant prop.",
      `Deliver the material primarily as ${input.targetFormat.toLowerCase()}.`,
    ],
  };
}
